### ISSUE TITLE
Create projects for the main sub topics we have to ogranize issues visually

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni#18]
I just tried to add ticket  #17  to a projects, and noticed that we might want to create projects for the different topic, at least, 

* djinni-generator
* support-lib  
* examples

Names might be subject to discuss, since naming is hard ;-)

**Comment by jothepro** [comment]
I'm thinking about this for a while now, still not sure what makes sense. If we will proceed splitting the project into multiple repos it may get confusing. Maybe we should have a new project for the splitting instead? 🤷

**Comment by a4z** [comment]
just to be sure, we are both talking about this projects, yes? 
https://github.com/cross-language-cpp/djinni/projects

what I suggest is, adding 3 new ones, so that each project in future has a own board (examples seen as 1 project)

but I am now unsure what you mean with a new project for the splitting, creating one project for the tasks of creating sub projects and adding the code ? 

If, than I think that can be tasks on the projects to each repo (examples seen as 1 project)

**Comment by jothepro** [comment]
> just to be sure, we are both talking about this projects, yes?

Yes, I think so.

> but I am now unsure what you mean with a new project for the splitting

My understanding is that projects are tied to a repository. So if we are going to split up the repo as I suggested it in #17, the 3 projects as you suggested them would become obsolete (because then every repo will have it's own issues, no need for multiple projects. Thats why I was suggesting to have a project for splitting up the repo, and then in the future track issues in the related repo.

But maybe I'm overthinking stuff, this is all speculations right now. If you have an idea on how to better organize our issues right now, go for it, I trust you! :)

**Comment by jothepro** [comment]
ok I figured out that you can also create projects on an organisation level, is that what you are suggesting? This may make a lot of sense in the future!:)

**Comment by a4z** [comment]
> ok I figured out that you can also create projects on an organisation level, is that what you are suggesting? This may make a lot of sense in the future!:)

yes, and I think you can add issues to whatever project you want, so we could also have multiple boards for the monorepo,
so the things are split into topics

I guess best would be to just create the project boards, then check out how this works in practice

**Comment by a4z** [comment]
I think it is safe to close this issue sine we are done with moving everything into own projects.
