### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by paulocoutinhox** [cross-language-cpp/djinni#22]
Hi,

What is the status of this project?

What is the difference between it and oficial and abandoned project?

Im using this today "https://github.com/hiennguyenle/finn".

And i have a project that depends on it (https://github.com/ezored/ezored).

Thanks.

**Comment by a4z** [comment]
I have seen ezored and it's components already previously, very impressive work

The status of this project is that we are working on it, slowly but constant. 
We have split the project into multiple parts, since those are more easy to maintain, especially when it comes to CI/CD, and it opens also a few other possibilities.
You can read more about the thoughts behind this decision in https://github.com/cross-language-cpp/djinni/issues/17

the generator is in good shape, the support lib need a bit more work, documentation is coming

**Comment by a4z** [comment]
Documentation is now available, see https://djinni.xlcpp.dev

Also the readme of this repo is updated, so I think this issue is resolved.
If you have any more questions, Paulo, please feel free to come back to us!
