### ISSUE TITLE
Convert Djinni Source to C++

### ISSUE THREAD

**Issue by bojanin** [cross-language-cpp/djinni#8]
Benefits:
* Current project owners know C++
* Speed (might be negligable?)

cons:
* Pretty heavy time sync?
* rewrite of source requires rewrite of many scripts across the project as well

@a4z @jothepro thoughts?

**Comment by jothepro** [comment]
Re-writing the project may be an interesting undertaking, but I have some serious concerns about it:
- It would be a damn lot of work. I think we should only invest this much when there is really no other option. Being inefficient in maintaining the current codebase still seems a lot easier than doing a rewrite.
- We don't know the current codebase very well (yet). In my opinion re-writes are a good idea if one has learned from it's mistakes. But being new to the codebase we might risk doing the same mistakes again (including choosing a proper language for the implementation)
- C++ does not seem like the right option for something like this to me. This would require some more research but I think my favorite would be python, because it allows to write very compact and meaningful code without all the verbosity c++ is known for.
- We'd loose support from former djinni developers, because they don't know the codebase any more.
- I don't know how good the tests are (yet). Without being a 100% sure that the tests are precise enough, we might risk to break stuff without even knowing it.

Apart from that I'm not event sure if I dislike scala as the chosen language. I skimmed over the parser this morning and it seemed pretty readable to me, even without knowing scala at all. But I've not yet attemted to modify it, you may already have deeper insights into the codebase.

**Comment by a4z** [comment]
My 2 Cents on this topic

## The short version:
Even if I might know C++ best, I do not care too much about which language is used anymore (as long as it is nothing super exotic)
But why not, just, I do not think that this should happen in this repository, because this would make things messy.
So maybe just start with a real greenfield project in the github organization, name it djinni-cpp and see what happens.
But I am unsure if I can get enthusiastic about a work from which I can not estimate what it requires and how long it might take.


## The long version: 
The djinni generator takes import source and generates output sources
If you know the input, you know the output.
If you have a good set of tests, you can change/add djinni generators with different implementation on a daily base.


### The parser and generator

#### Parser
(Please be aware that parsing is nothing that has ever been part or my daily job, so this part could be full of errors.)

I am not sure if anyone would love to use boost::sprit for parsing djinni files. Or using the C++11 std regex to do the parsing.
So, ... what to use? 

It looks like the current parsing is base on regex + string matching. Which is easy to start with for such a project.
But as such projects grow, it can quickly become complicated. Not sure if this state has been reached, but I would not be surprised.

But luckily this work exists, and we can look at it and learn from that.

##### What questions pop up

For example:
Should we not have a little bit more formalized specification approach. (grammar) ?
If we would have a grammar, and use a tool like Antlr, than Antlr could generate the base for many different languages to implement the code generators 

#### Generator 

Is everything needed generated, what is today missing?
Example: I have a hard time to transport Exceptions to Swift (not possible), could there be done something? 

### Support lib

This seems to be pretty OK at the moment, even if I could imaging the one or the other feature could be needed

But I need to learn if this fulfills everything that is required, or are there new requirements, possible improvements since kotlin swift etc gives more possibilities ... 

### Summary
When having this, some specification, some testing , some idea about the grammar, parsing and generator, I would look at which technologies would fit best.

With more idea about all that time estimations could be possible, because, currently I have no idea what 'lets re-write that in C++, or any other language' would mean.

But seriously, this is all longer term future I think.
My thinking is: Stabilize current state, make it more accessible / usable for people
Look at it and learn, then see how it could be improved.

**Comment by bojanin** [comment]
Very good points made by both of you. 
After further thought my idea then is to wait until we have a deeper understanding of the codebase and then perhaps revisit this ticket down the road? 

A couple final thoughts: 
@jothepro I also would prefer python as it is simpler than C++.
@a4z ANTLR would be a nice to have tool, I have used it before (although its been some years) and its powerful.

**Comment by mjmacleod** [comment]
Some thoughts.

Scala:
* I don't think scala is necessarily a bad language choice for something like this
* However its not a language that I am very fluent in and this makes (for me at least) doing changes to the codebase challenging
* Which makes me inclined to keep any changes I make on my own personal fork (where we have some hacked in node_js support for instance), because I'm not confident that what I'm doing is really quality enough for others to use
* Others seem to also feel this way
* Mobile cpp development community is already quite small, and having the tools in a language that only a small subset of that already small group is likely comfortable with really limits the opportunity to have a broader base of contributors
* To me the scala *parser* code is reasonably concise and not too terrible to work with, but I've struggled to make changes to the generator at times it doesn't seem as good a fit there.

C++:
* C++ probably is not technically the best language for something like this
* However it does have the distinct advantage of being the one language that almost everyone that ever wants to get involved in this project is likely to be relatively fluent in.
* Which might be a distinct advantage, I wouldn't dismiss it too quickly
* A C++ port should likely use either a parser generator like ANTLR for the parser part anyway - if it were to be implemented in raw C++ I guess my choice would be boost::xpressive as its possible to do quite concise and very BNF-like rules using xpressive 

Python:
* I think would also be a reasonable choice
* I'm never personally wildly enthusiastic about working with python, but at the same time its not 'exotic' and I can do it without too much hassle - I echo other sentiments here that ultimately any language is really fine as long as its something that isn't overly exotic
* There is at least IMO a higher possibility of developers who are interested being able to contribute to a Python project than a Scala one so in that regard I think Python would be a much better choice than Scala

General thoughts:
* I agree that changing languages right now would probably be a mistake, primarily because its a large task upfront that could kill the momentum of something that has just started
* I do think (based on my experience of trying to make changes so far), that a language change will become necessary down the line however, unless the project is to remain maintained by a very small team of people who are comfortable enough to make changes (which is I think the mistake the original djinni team made, and shouldn't be repeated)
* At a bare minimum such a change would require thorough unit tests first (which anyway should be a first goal), so that it can be ensured that the port handles everything right.
* So I agree ultimately with this "My thinking is: Stabilize current state, make it more accessible / usable for people
Look at it and learn, then see how it could be improved." - it seems sensible.

**Comment by a4z** [comment]
>     * Which makes me inclined to keep any changes I make on my own personal fork (where we have some hacked in node_js support for instance), because I'm not confident that what I'm doing is really quality enough for others to use
> 
>     * Others seem to also feel this way
> 

I heard recently on some podcast, I think it was from Gui Rambo, something like: There is a lot of software on peoples computers that should be released/is waiting to be released ? ...
What he meant it that too often people want to make code nice and perfect before sharing it, and then the code never will be shared because it never will be nice and perfect.

I guess what I want to say is, Malcolm - but this is valid for everyone, is, just make your changes visible, the worst that can happen is that someone suggests improvements.  Or, people start to use it and you have additional users :-)

**Comment by mjmacleod** [comment]
Sure, its not so much a case that I'm embarrassed to share it or anything like that.
Its publicly available (https://github.com/mjmacleod/djinni/tree/gulden) 

Its just not something I would necessarily try put in a pull request for, especially not to the previous dropbox repo which had a pretty high bar for accepting changes, because it takes various shortcuts in implementation that are okay for my needs but are likely not great for other peoples needs, and makes other changes to parts of the codebase that might not actually be suitable etc.
Many of these shortcuts were taken because I simply didn't have the time (or expertise) to change the Scala code in a cleaner way...
If I'd been working in a language I'm more comfortable with I probably would have just done it right the first time.

Not saying I won't try do a pull request with these changes at some point to this repo, its been a bit of a bad year so currently a bit low on time, but when things settle down I'll probably try clean it up a bit and do just that - more just trying to explain how (in my opinion at least) the Scala tends to act as an additional barrier that might keep away those who might otherwise contribute.

**Comment by a4z** [comment]
thank you Malcolm for sharing your changes! yes time is a major issue, I have also to notice that :) 

General question to all involved people, shall we close this ticket? 
From my point, I think most aspects of the topic have been handled.

**Comment by jothepro** [comment]
FYI: There already seems to exist an attemt to re-write djinni in python: https://github.com/pyginny/pyginny
It has not seen any activity since the initial commit, but I will have an eye on it.

@a4z I'd be ok with closing the ticket, as to me it seems like we have gained enough of a common sense on this topic for now.

**Comment by a4z** [comment]
just a side note,  if we do #17, integrating such re-writes like the python one you point to @jothepro , would be a much more easy task.

Since there are no protest about closing the ticket, lets close it, if we do the split, there will be nothing hinder anyone of having competing implementations of a generator, even one in C++
